-- =============================================================================
-- Jornada da Prosperidade: 21 dias pra aprender a merecer
-- Query idempotente: cria/atualiza a jornada e carrega todos os dias
-- (reflexão + pergunta + tarefa). Pode rodar e re-rodar.
-- Pré-requisito (uma vez): 0010 (tabelas + RLS), 0011 e 0014.
-- =============================================================================
alter table prosperidade_jornada_arcos add column if not exists tarefa   text;
alter table prosperidade_jornada_arcos add column if not exists reflexao text;

insert into prosperidade_jornadas (slug, titulo, subtitulo, convite, dias, intervalo_horas, ordem, ativa, fronteira)
values ($v$merecer$v$, $v$21 dias pra aprender a merecer$v$, $v$aprender a receber sem precisar merecer$v$, $v$Vinte e um dias pra olhar de perto o quanto você acha que precisa merecer pra receber, e ir afrouxando esse nó. Um degrau por dia, no seu ritmo. Se sumir, eu te espero, e a gente continua de onde parou.$v$, 21, 24, 1, true, NULL)
on conflict (slug) do update set
  titulo = excluded.titulo, subtitulo = excluded.subtitulo, convite = excluded.convite,
  dias = excluded.dias, ordem = excluded.ordem, fronteira = excluded.fronteira;

insert into prosperidade_jornada_arcos (jornada_id, dia, reflexao, prompt, tarefa, fechamento)
select j.id, v.dia, v.reflexao, v.prompt, v.tarefa, v.fechamento
from prosperidade_jornadas j
join (values
  (1, $v$Merecer descanso parece simples, mas repara numa coisa: você provavelmente só descansa depois de cumprir uma lista, como se o descanso fosse pagamento por serviço prestado. Hoje a gente olha pra essa moeda de troca, de onde ela veio, e se ela é mesmo sua.$v$, $v$O que você acha que precisa fazer pra merecer descanso?$v$, $v$Hoje, descanse dez minutos sem ter terminado nada antes. Sente, respire, olhe pela janela. Só porque sim, não porque ganhou.$v$, false),
  (2, $v$A gente aprende que tudo de bom precisa ser conquistado com suor. Mas se você olhar com calma, muita coisa boa chegou sem você ter feito por merecer: um encontro, uma ajuda, uma sorte. Não é pra diminuir o seu esforço, é pra lembrar que receber nem sempre é uma fatura.$v$, $v$Uma coisa boa que te aconteceu sem você ter “merecido” por esforço?$v$, $v$Hoje, quando algo bom acontecer, por menor que seja, em vez de pensar “mereço” ou “não mereço”, experimente só dizer pra você: isso chegou, e tudo bem receber.$v$, false),
  (3, $v$Ninguém nasce achando que precisa provar valor. Isso é ensinado, geralmente cedo, geralmente por alguém que também aprendeu assim. Hoje não é pra culpar ninguém, é pra ver de onde veio essa régua, porque o que a gente enxerga, a gente pode escolher se ainda serve.$v$, $v$De quem você aprendeu que precisa provar valor pra receber?$v$, $v$Hoje, repare uma vez em que você se pegou provando algo que ninguém pediu. Só repare, não precisa mudar nada ainda.$v$, false),
  (4, $v$Quando alguém te elogia e você responde “imagina, foi sorte” ou “qualquer uma faria”, você está devolvendo um presente sem abrir. O elogio é algo que te oferecem, e desconversar é um jeito de dizer que você não merece segurar aquilo. Hoje a gente treina abrir.$v$, $v$Um elogio que você desconversou em vez de receber?$v$, $v$Hoje, se alguém te elogiar, responda só “obrigada”. Sem emenda, sem diminuir. Sinta como é segurar o elogio inteiro.$v$, false),
  (5, $v$O corpo sabe antes da cabeça. Quando alguém te dá algo, um presente, um favor, um carinho, às vezes aperta, dá vontade de retribuir na hora, de não ficar devendo. Esse aperto conta uma história sobre o quanto você se permite simplesmente receber.$v$, $v$O que muda no seu corpo quando alguém te dá algo?$v$, $v$Hoje, se você receber algo, repare na primeira reação do seu corpo antes de agir. Só observe, sem corrigir.$v$, false),
  (6, $v$A gente costuma ser uma juíza dura consigo e uma amiga doce com as outras. Você diria pra uma amiga cansada “você devia ter feito mais”? Provavelmente não. Mas diz pra você. Hoje a gente repara nessa diferença de tratamento.$v$, $v$Você cobra de si o que jamais cobraria de uma amiga?$v$, $v$Hoje, quando você se pegar se cobrando, pergunte: eu diria isso pra alguém que amo? Se não, experimente falar com você do jeito que falaria com ela.$v$, false),
  (7, $v$Chegamos ao fim da primeira semana. Você passou dias olhando pra ideia de que precisa fazer por merecer. Hoje a gente vira a chave: e se algumas coisas você merece só por estar aqui, viva, inteira, sem ter que apresentar comprovante?$v$, $v$Uma coisa que você merece hoje, sem motivo, só por existir?$v$, $v$Hoje, dê a você essa uma coisa. Pequena que seja. Não como recompensa, como direito.$v$, false),
  (8, $v$Receber e ficar devendo viraram quase a mesma coisa pra muita gente. Alguém te ajuda e já vem o “preciso retribuir”. Hoje a gente separa as duas: dá pra receber sem que isso abra uma conta a pagar.$v$, $v$Quando você se sente em dívida por receber?$v$, $v$Hoje, se alguém fizer algo por você, agradeça e resista ao impulso de retribuir na mesma hora. Deixe o gesto ser só um gesto.$v$, false),
  (9, $v$Tem uma fila invisível onde você costuma ficar atrás de todo mundo: dos filhos, do trabalho, da casa, das outras pessoas. As suas necessidades esperam uma vez que quase nunca chega. Hoje a gente olha pra essa fila.$v$, $v$Uma necessidade sua que você sempre põe por último?$v$, $v$Hoje, atenda uma necessidade sua antes de atender a de outra pessoa. Uma vez só. Veja o que acontece, por dentro e por fora.$v$, false),
  (10, $v$Quando uma menina pede algo com os olhos brilhando, a gente não responde “você não merece” nem “primeiro prove que dá conta”. A gente quer dar. Essa menina ainda mora em você, e ela continua pedindo.$v$, $v$O que você daria a uma menina de 8 anos que pedisse o que você quer?$v$, $v$Hoje, faça por você uma coisa pequena que daria pra essa menina. Do jeito que daria pra ela: sem condição, com carinho.$v$, false),
  (11, $v$Cada “sim” que você dá com o coração apertado é um “não” que você negou a si mesma. Agradar virou um jeito de garantir que não te abandonem. Hoje a gente repara no preço disso.$v$, $v$Um “não” que você não deu por achar que devia agradar?$v$, $v$Hoje, dê um “não” pequeno a algo que você diria “sim” só por agradar. Pode ser mínimo. O músculo se aprende no pequeno.$v$, false),
  (12, $v$Antes de qualquer raciocínio, o dinheiro entrando mexe com algo. Pra umas, alívio; pra outras, medo de perder, culpa, ou a pressa de já destinar tudo. Esse primeiro sentimento conta a sua relação real com receber, não a que você gostaria de ter.$v$, $v$Dinheiro entrando: o que você sente antes de pensar?$v$, $v$Hoje, se entrar algum dinheiro, ou se imaginar entrando, pare um segundo e nomeie o primeiro sentimento. Sem julgar, só nomeie.$v$, false),
  (13, $v$“Já tá bom” é uma frase que protege e aprisiona ao mesmo tempo. Ela te poupa da decepção de querer, mas também tampa o desejo antes dele respirar. Hoje a gente pergunta se o “já tá bom” é paz ou é medo disfarçado.$v$, $v$Você se permite querer mais, ou se censura no “já tá bom”?$v$, $v$Hoje, deixe-se querer uma coisa sem se justificar. Não precisa ir atrás ainda, só admita pra você que quer.$v$, false),
  (14, $v$Metade do caminho. Você vem esperando, talvez a vida toda, que alguém te autorize: a descansar, a querer, a receber, a ocupar espaço. Hoje a gente para de esperar. A permissão que não veio de fora pode vir de você.$v$, $v$Escreva pra você mesma a permissão que ninguém te deu.$v$, $v$Hoje, leia em voz alta a permissão que você escreveu. Pra você mesma, no espelho ou só pro ar. Deixe seu corpo ouvir.$v$, false),
  (15, $v$O “quando der” é um tempo que não existe no calendário. A consulta, o descanso, o curso, a viagem, tudo que é seu fica esperando uma folga que você nunca se dá. Hoje a gente olha pra esse cuidado adiado.$v$, $v$Um cuidado que você adia “pra quando der”?$v$, $v$Hoje, dê o primeiro passo mínimo nesse cuidado: marque, pesquise, agende. Não o cuidado inteiro, só o primeiro centímetro.$v$, false),
  (16, $v$Tem um teto invisível feito do olhar dos outros: “vão achar que sou gananciosa, que tô me achando, que não mereço”. Esse medo decide quanto você se permite ter antes mesmo de você tentar. Hoje a gente ilumina ele.$v$, $v$O que você teme que pensem se você receber demais?$v$, $v$Hoje, repare se você diminuiu algo seu na frente de alguém pra não parecer “demais”. Só repare a cena.$v$, false),
  (17, $v$Dar é confortável, te mantém no controle, na posição de quem pode. Receber expõe, te coloca na posição de quem precisa. Por isso, pra muita mulher forte, receber é a parte mais difícil. Hoje a gente honra essa dificuldade.$v$, $v$Uma vez em que receber foi mais difícil que dar?$v$, $v$Hoje, peça uma ajuda pequena a alguém, algo que você normalmente faria sozinha. Pratique o lado incômodo.$v$, false),
  (18, $v$Provar cansa. É um trabalho invisível e sem fim, porque a régua sempre sobe. Depois de tantos dias olhando pra isso, talvez já dê pra largar alguma prova que você carrega faz tempo. Hoje a gente escolhe o que soltar.$v$, $v$O que você está pronta pra parar de provar?$v$, $v$Hoje, em uma situação, não prove nada. Não justifique, não mostre serviço, não se explique. Só esteja.$v$, false),
  (19, $v$Imagina por um instante que tudo já é seu por direito: o descanso, o prazer, o cuidado, o querer. Você não precisa ganhar nada. Como seria viver um dia assim? Essa imaginação não é fuga, é um ensaio do possível.$v$, $v$Como seria seu dia se você não precisasse merecer nada?$v$, $v$Hoje, viva uma hora desse dia imaginado. Escolha uma hora e, nela, não mereça nada: só receba e exista.$v$, false),
  (20, $v$Estamos quase no fim. Tudo que a gente olhou só vira mudança quando vira gesto. Amanhã a jornada fecha, mas a sua permissão continua. Hoje a gente combina uma coisa concreta que você vai se dar nos próximos dias.$v$, $v$Uma coisa que você vai se permitir esta semana?$v$, $v$Hoje, marque na agenda, ou diga em voz alta, quando você vai se permitir essa coisa. Dê data pra ela.$v$, false),
  (21, $v$Vinte e um dias atrás você começou perguntando o que precisava fazer pra merecer descanso. Hoje a Val olha com você todo o caminho que você fez, o que reconheceu, o que mudou no seu jeito de receber.$v$, $v$Olhando pra trás, o que mudou em você sobre merecer e receber? (a Val devolve o arco inteiro, dia a dia)$v$, $v$Hoje, escolha uma frase que você quer levar dessa jornada e guarde onde você veja. Foi você que aprendeu, não foi ninguém que te deu.$v$, true)
) as v(dia, reflexao, prompt, tarefa, fechamento) on j.slug = $v$merecer$v$
on conflict (jornada_id, dia) do update set
  reflexao = excluded.reflexao, prompt = excluded.prompt,
  tarefa = excluded.tarefa, fechamento = excluded.fechamento;
