-- =============================================================================
-- Jornada da Prosperidade: 21 dias de prosperidade nas pequenas coisas
-- Query idempotente: cria/atualiza a jornada e carrega todos os dias
-- (reflexão + pergunta + tarefa). Pode rodar e re-rodar.
-- Pré-requisito (uma vez): 0010 (tabelas + RLS), 0011 e 0014.
-- =============================================================================
alter table prosperidade_jornada_arcos add column if not exists tarefa   text;
alter table prosperidade_jornada_arcos add column if not exists reflexao text;

insert into prosperidade_jornadas (slug, titulo, subtitulo, convite, dias, intervalo_horas, ordem, ativa, fronteira)
values ($v$pequenas-coisas$v$, $v$21 dias de prosperidade nas pequenas coisas$v$, $v$a abundância que já está aqui, e some de tão perto$v$, $v$Vinte e um dias pra reparar na fartura que já mora na sua vida e ficou invisível de tão próxima. Um dia por vez, sem pressa. Pode pausar e voltar quando quiser, daqui mesmo.$v$, 21, 24, 2, true, NULL)
on conflict (slug) do update set
  titulo = excluded.titulo, subtitulo = excluded.subtitulo, convite = excluded.convite,
  dias = excluded.dias, ordem = excluded.ordem, fronteira = excluded.fronteira;

insert into prosperidade_jornada_arcos (jornada_id, dia, reflexao, prompt, tarefa, fechamento)
select j.id, v.dia, v.reflexao, v.prompt, v.tarefa, v.fechamento
from prosperidade_jornadas j
join (values
  (1, $v$A gente se acostuma rápido com o que conquista. O que um dia foi um sonho distante hoje é rotina invisível: a casa, o trabalho, a pessoa ao lado, o copo de café. Hoje a gente desacostuma pra ver de novo.$v$, $v$Algo que você usou hoje e que um dia foi um sonho?$v$, $v$Hoje, ao usar essa coisa, pare um segundo e lembre de quando ela era só desejo. Deixe a memória te alcançar.$v$, false),
  (2, $v$Água quente que sai da torneira, luz que acende no escuro, um teto que segura a chuva. Conforto que vira invisível de tão constante. Não é pra sentir culpa por ter, é pra voltar a ver o que já está aqui te sustentando.$v$, $v$Um conforto tão presente que virou invisível?$v$, $v$Hoje, use um desses confortos com atenção plena, uma vez. Sinta a água morna, a luz, o agasalho, como se fosse a primeira vez.$v$, false),
  (3, $v$Nem tudo de bom você foi atrás. Algumas pessoas simplesmente apareceram e ficaram, trazendo cor sem você ter planejado. Hoje a gente repara nessa abundância que chegou de graça, em forma de gente.$v$, $v$Alguém que apareceu na sua vida sem você buscar?$v$, $v$Hoje, mande uma mensagem curta pra essa pessoa. Não precisa explicar a jornada, só diga que lembrou dela.$v$, false),
  (4, $v$Seu corpo faz milhares de coisas sem você pedir: respira, te leva de um lugar a outro, abraça, prova um sabor, escuta uma música. A gente só repara nele quando dói. Hoje a gente repara quando funciona.$v$, $v$Uma habilidade do seu corpo que você não agradece?$v$, $v$Hoje, use essa habilidade com presença. Se é andar, ande reparando nos passos. Se é ver, olhe algo bonito de propósito.$v$, false),
  (5, $v$Toda casa tem um canto que é mais seu, onde o corpo relaxa sozinho: uma cadeira, um pedaço de chão com sol, a cozinha de manhã. Esse canto é uma riqueza pequena e diária. Hoje a gente o reconhece.$v$, $v$Um lugar da sua casa que te acolhe?$v$, $v$Hoje, passe cinco minutos nesse lugar sem fazer nada útil. Só estar ali, deixando ele te acolher.$v$, false),
  (6, $v$O prazer de comer algo gostoso é uma abundância que se repete todo dia e quase sempre passa batida, no automático, na pressa. Hoje a gente desacelera pra sentir essa, que é das alegrias mais simples e disponíveis.$v$, $v$Uma comida que te deu prazer recente?$v$, $v$Hoje, coma uma coisa devagar, prestando atenção no sabor. Sem tela, sem pressa. Só você e o gosto.$v$, false),
  (7, $v$Uma semana olhando pras pequenas coisas. Hoje a gente junta: um dia comum seu é cheio de coisas boas que você nem conta. Vamos contar. Não pra romantizar a vida, pra ver o que sempre esteve ali.$v$, $v$A abundância de um dia comum seu, listada. O que cabe num dia qualquer?$v$, $v$Hoje, ao deitar, conte de cabeça três coisas boas que o dia comum te deu. Adormeça com a lista.$v$, false),
  (8, $v$Você sabe coisas hoje que pareceriam impossíveis pra você de anos atrás. Esse conhecimento foi construído tijolo por tijolo, e virou tão seu que parece que sempre soube. Hoje a gente reconhece essa riqueza que mora em você.$v$, $v$Um conhecimento que você tem e levou anos pra construir?$v$, $v$Hoje, ensine ou compartilhe uma pontinha desse conhecimento com alguém. Veja o valor dele pelos olhos de quem não sabe.$v$, false),
  (9, $v$Tem gente torcendo por você em silêncio, de longe, sem você nem saber. Alguém que fala bem de você quando você não está, que te guarda no pensamento. Essa torcida invisível também é parte da sua riqueza.$v$, $v$Uma pessoa que torce por você de longe?$v$, $v$Hoje, imagine essa pessoa torcendo por você. Deixe a sensação de ser bem-querida te alcançar por um momento.$v$, false),
  (10, $v$A chuva, um pássaro, uma música que você ama, a voz de alguém, o silêncio da manhã. Sons que fazem bem e estão quase sempre ao alcance, de graça. Hoje a gente repara nessa abundância que entra pelos ouvidos.$v$, $v$Um som que te faz bem e está sempre disponível?$v$, $v$Hoje, pare um minuto só pra ouvir esse som. Olhos fechados, se der. Deixe ele te preencher.$v$, false),
  (11, $v$Liberdade, muitas vezes, é poder escolher. E você provavelmente tem hoje escolhas que um dia não teve: o que comer, com quem ficar, como gastar uma hora, pra onde ir. Hoje a gente reconhece essa abundância de poder escolher.$v$, $v$Uma escolha que hoje você tem e antes não tinha?$v$, $v$Hoje, faça uma escolha pequena com consciência de que pode escolher. Saboreie o poder de decidir, mesmo numa coisa boba.$v$, false),
  (12, $v$O sol que aquece, o ar que você respira, o céu que muda de cor, uma árvore no caminho. A natureza distribui beleza e vida sem cobrar, todo dia. Hoje a gente recebe esse presente que não tem fatura.$v$, $v$Algo da natureza que te foi dado de graça hoje?$v$, $v$Hoje, fique um momento ao ar livre, ou só na janela, recebendo algo da natureza de propósito: sol no rosto, vento, o verde.$v$, false),
  (13, $v$Sem comparar pra se sentir melhor que ninguém, mas pra ver com honestidade: a sua vida tem facilidades que pra muita gente seriam sonho. Reconhecer isso não tira a sua luta, só amplia a sua visão do que já é seu.$v$, $v$Uma facilidade da sua vida que muita gente não tem?$v$, $v$Hoje, use essa facilidade reparando que ela é uma facilidade. Sem culpa, só com consciência.$v$, false),
  (14, $v$Metade da jornada das pequenas coisas. “Suficiente” é uma palavra que a pressa não deixa a gente sentir, porque sempre falta algo no horizonte. Hoje a gente para e pergunta o que já basta, de verdade.$v$, $v$O que “ter o suficiente” significa pra você hoje?$v$, $v$Hoje, escolha uma área da vida e diga pra você: nessa, eu já tenho o suficiente. Sinta como é descansar nessa frase.$v$, false),
  (15, $v$As fases difíceis cobram caro, mas às vezes deixam algo que virou riqueza: uma força, uma sabedoria, um limite que você aprendeu a respeitar. Hoje a gente não romantiza a dor, só reconhece o que ela te deixou de bom.$v$, $v$Um aprendizado que veio de uma fase difícil?$v$, $v$Hoje, agradeça em silêncio à sua versão que atravessou aquela fase. Ela construiu algo que você usa até hoje.$v$, false),
  (16, $v$A beleza não espera ocasião especial. Ela está no vapor do café, na luz da tarde, num gesto de alguém, e quase sempre passa porque a gente está olhando pra dentro da pressa. Hoje a gente treina o olho pra capturar.$v$, $v$Uma beleza pequena que você quase não viu hoje?$v$, $v$Hoje, cace três belezas pequenas de propósito. Olhe pro mundo como quem procura, e elas aparecem.$v$, false),
  (17, $v$A gente pensa muito em quem faz falta pra nós, e pouco em pra quem nós fazemos falta. Mas você é abundância na vida de alguém: a sua presença importa, o seu sumiço pesa. Hoje a gente reconhece o seu valor pra fora.$v$, $v$Alguém a quem você faz falta?$v$, $v$Hoje, deixe-se ser presença pra essa pessoa: uma ligação, uma visita, uma mensagem. Ocupe o espaço que é seu na vida dela.$v$, false),
  (18, $v$Abundância não é só o que você usa, é também o que está guardado esperando: um talento parado, um contato que você não aciona, um saber que não aplica. Riqueza adormecida ainda é riqueza. Hoje a gente acorda uma.$v$, $v$Um recurso seu (tempo, rede, saber) parado, esperando uso?$v$, $v$Hoje, dê um primeiro movimento mínimo pra usar esse recurso: um e-mail, uma ligação, uma anotação. Tire ele da gaveta.$v$, false),
  (19, $v$Enquanto a gente lamenta as portas fechadas, costuma ter uma aberta que a gente nem olha: uma oportunidade, um convite, um caminho disponível agora. Hoje a gente repara no que está aberto, não no que travou.$v$, $v$Uma porta que está aberta pra você agora?$v$, $v$Hoje, olhe pra essa porta aberta e dê um passo na direção dela. Pequeno, só pra sentir que ela é real.$v$, false),
  (20, $v$Você de dez anos atrás sonhava com coisas que hoje você tem e nem repara. Olhar pra trás assim não é nostalgia, é prova: você já chegou onde um dia quis chegar, em muita coisa. Hoje a gente vê isso.$v$, $v$O que você já tem que a sua versão de 10 anos atrás invejaria?$v$, $v$Hoje, agradeça à sua versão de dez anos atrás por ter caminhado até aqui. E diga a ela: deu certo, em muita coisa deu.$v$, false),
  (21, $v$Vinte e um dias atrás você começou olhando pra algo que um dia foi sonho. A Val acompanhou cada pequena coisa que você nomeou, e hoje mostra a você o tamanho da abundância que sempre esteve aí, esperando o seu olhar.$v$, $v$Depois de 21 dias, o que mudou no seu jeito de olhar pro que você já tem? (a Val mostra quanta abundância você nomeou)$v$, $v$Hoje, escolha um momento do dia pra ser, todo dia, o seu momento de reparar numa pequena coisa. A jornada acaba, o olhar fica.$v$, true)
) as v(dia, reflexao, prompt, tarefa, fechamento) on j.slug = $v$pequenas-coisas$v$
on conflict (jornada_id, dia) do update set
  reflexao = excluded.reflexao, prompt = excluded.prompt,
  tarefa = excluded.tarefa, fechamento = excluded.fechamento;
